Do not pass _FORTIFY_SOURCE=2 on POSIX debug builds.
This fixes the build on Linux at least, where passing _FORTIFY_SOURCE=2 and
-O0 failed like this:

In file included from ../../benchmark/unordered_map_benchmark.cc:5:
In file included from ../../third_party/libc++/trunk/include/random:1635:
In file included from ../../third_party/libc++/trunk/include/__config:186:
/usr/include/features.h:381:4: error: _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror,-W#warnings]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
    1 error generated.

This solution is similar to what Chromium does in its own
//build/config/compiler/BUID.gn.

Change-Id: Icf2c27b4f4dd0a6216fd19228252b872b90ebc9f